# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/james/projects/GPUE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/james/projects/GPUE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/james/projects/GPUE/CMakeFiles /home/james/projects/GPUE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/james/projects/GPUE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named unitTest

# Build rule for target.
unitTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unitTest
.PHONY : unitTest

# fast build rule for target.
unitTest/fast:
	$(MAKE) -f CMakeFiles/unitTest.dir/build.make CMakeFiles/unitTest.dir/build
.PHONY : unitTest/fast

#=============================================================================
# Target rules for targets named gpue

# Build rule for target.
gpue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gpue
.PHONY : gpue

# fast build rule for target.
gpue/fast:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/build
.PHONY : gpue/fast

src/ds.o: src/ds.cu.o

.PHONY : src/ds.o

# target to build an object file
src/ds.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/ds.cu.o
.PHONY : src/ds.cu.o

src/ds.i: src/ds.cu.i

.PHONY : src/ds.i

# target to preprocess a source file
src/ds.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/ds.cu.i
.PHONY : src/ds.cu.i

src/ds.s: src/ds.cu.s

.PHONY : src/ds.s

# target to generate assembly for a file
src/ds.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/ds.cu.s
.PHONY : src/ds.cu.s

src/dynamic.o: src/dynamic.cu.o

.PHONY : src/dynamic.o

# target to build an object file
src/dynamic.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/dynamic.cu.o
.PHONY : src/dynamic.cu.o

src/dynamic.i: src/dynamic.cu.i

.PHONY : src/dynamic.i

# target to preprocess a source file
src/dynamic.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/dynamic.cu.i
.PHONY : src/dynamic.cu.i

src/dynamic.s: src/dynamic.cu.s

.PHONY : src/dynamic.s

# target to generate assembly for a file
src/dynamic.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/dynamic.cu.s
.PHONY : src/dynamic.cu.s

src/edge.o: src/edge.cu.o

.PHONY : src/edge.o

# target to build an object file
src/edge.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/edge.cu.o
.PHONY : src/edge.cu.o

src/edge.i: src/edge.cu.i

.PHONY : src/edge.i

# target to preprocess a source file
src/edge.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/edge.cu.i
.PHONY : src/edge.cu.i

src/edge.s: src/edge.cu.s

.PHONY : src/edge.s

# target to generate assembly for a file
src/edge.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/edge.cu.s
.PHONY : src/edge.cu.s

src/evolution.o: src/evolution.cu.o

.PHONY : src/evolution.o

# target to build an object file
src/evolution.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/evolution.cu.o
.PHONY : src/evolution.cu.o

src/evolution.i: src/evolution.cu.i

.PHONY : src/evolution.i

# target to preprocess a source file
src/evolution.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/evolution.cu.i
.PHONY : src/evolution.cu.i

src/evolution.s: src/evolution.cu.s

.PHONY : src/evolution.s

# target to generate assembly for a file
src/evolution.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/evolution.cu.s
.PHONY : src/evolution.cu.s

src/fileIO.o: src/fileIO.cu.o

.PHONY : src/fileIO.o

# target to build an object file
src/fileIO.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/fileIO.cu.o
.PHONY : src/fileIO.cu.o

src/fileIO.i: src/fileIO.cu.i

.PHONY : src/fileIO.i

# target to preprocess a source file
src/fileIO.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/fileIO.cu.i
.PHONY : src/fileIO.cu.i

src/fileIO.s: src/fileIO.cu.s

.PHONY : src/fileIO.s

# target to generate assembly for a file
src/fileIO.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/fileIO.cu.s
.PHONY : src/fileIO.cu.s

src/init.o: src/init.cu.o

.PHONY : src/init.o

# target to build an object file
src/init.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/init.cu.o
.PHONY : src/init.cu.o

src/init.i: src/init.cu.i

.PHONY : src/init.i

# target to preprocess a source file
src/init.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/init.cu.i
.PHONY : src/init.cu.i

src/init.s: src/init.cu.s

.PHONY : src/init.s

# target to generate assembly for a file
src/init.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/init.cu.s
.PHONY : src/init.cu.s

src/kernels.o: src/kernels.cu.o

.PHONY : src/kernels.o

# target to build an object file
src/kernels.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/kernels.cu.o
.PHONY : src/kernels.cu.o

src/kernels.i: src/kernels.cu.i

.PHONY : src/kernels.i

# target to preprocess a source file
src/kernels.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/kernels.cu.i
.PHONY : src/kernels.cu.i

src/kernels.s: src/kernels.cu.s

.PHONY : src/kernels.s

# target to generate assembly for a file
src/kernels.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/kernels.cu.s
.PHONY : src/kernels.cu.s

src/lattice.o: src/lattice.cu.o

.PHONY : src/lattice.o

# target to build an object file
src/lattice.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/lattice.cu.o
.PHONY : src/lattice.cu.o

src/lattice.i: src/lattice.cu.i

.PHONY : src/lattice.i

# target to preprocess a source file
src/lattice.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/lattice.cu.i
.PHONY : src/lattice.cu.i

src/lattice.s: src/lattice.cu.s

.PHONY : src/lattice.s

# target to generate assembly for a file
src/lattice.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/lattice.cu.s
.PHONY : src/lattice.cu.s

src/manip.o: src/manip.cu.o

.PHONY : src/manip.o

# target to build an object file
src/manip.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/manip.cu.o
.PHONY : src/manip.cu.o

src/manip.i: src/manip.cu.i

.PHONY : src/manip.i

# target to preprocess a source file
src/manip.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/manip.cu.i
.PHONY : src/manip.cu.i

src/manip.s: src/manip.cu.s

.PHONY : src/manip.s

# target to generate assembly for a file
src/manip.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/manip.cu.s
.PHONY : src/manip.cu.s

src/minions.o: src/minions.cu.o

.PHONY : src/minions.o

# target to build an object file
src/minions.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/minions.cu.o
.PHONY : src/minions.cu.o

src/minions.i: src/minions.cu.i

.PHONY : src/minions.i

# target to preprocess a source file
src/minions.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/minions.cu.i
.PHONY : src/minions.cu.i

src/minions.s: src/minions.cu.s

.PHONY : src/minions.s

# target to generate assembly for a file
src/minions.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/minions.cu.s
.PHONY : src/minions.cu.s

src/multigpu.o: src/multigpu.cu.o

.PHONY : src/multigpu.o

# target to build an object file
src/multigpu.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/multigpu.cu.o
.PHONY : src/multigpu.cu.o

src/multigpu.i: src/multigpu.cu.i

.PHONY : src/multigpu.i

# target to preprocess a source file
src/multigpu.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/multigpu.cu.i
.PHONY : src/multigpu.cu.i

src/multigpu.s: src/multigpu.cu.s

.PHONY : src/multigpu.s

# target to generate assembly for a file
src/multigpu.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/multigpu.cu.s
.PHONY : src/multigpu.cu.s

src/node.o: src/node.cu.o

.PHONY : src/node.o

# target to build an object file
src/node.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/node.cu.o
.PHONY : src/node.cu.o

src/node.i: src/node.cu.i

.PHONY : src/node.i

# target to preprocess a source file
src/node.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/node.cu.i
.PHONY : src/node.cu.i

src/node.s: src/node.cu.s

.PHONY : src/node.s

# target to generate assembly for a file
src/node.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/node.cu.s
.PHONY : src/node.cu.s

src/operators.o: src/operators.cu.o

.PHONY : src/operators.o

# target to build an object file
src/operators.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/operators.cu.o
.PHONY : src/operators.cu.o

src/operators.i: src/operators.cu.i

.PHONY : src/operators.i

# target to preprocess a source file
src/operators.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/operators.cu.i
.PHONY : src/operators.cu.i

src/operators.s: src/operators.cu.s

.PHONY : src/operators.s

# target to generate assembly for a file
src/operators.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/operators.cu.s
.PHONY : src/operators.cu.s

src/parser.o: src/parser.cu.o

.PHONY : src/parser.o

# target to build an object file
src/parser.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/parser.cu.o
.PHONY : src/parser.cu.o

src/parser.i: src/parser.cu.i

.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/parser.cu.i
.PHONY : src/parser.cu.i

src/parser.s: src/parser.cu.s

.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/parser.cu.s
.PHONY : src/parser.cu.s

src/split_op.o: src/split_op.cu.o

.PHONY : src/split_op.o

# target to build an object file
src/split_op.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/split_op.cu.o
.PHONY : src/split_op.cu.o

src/split_op.i: src/split_op.cu.i

.PHONY : src/split_op.i

# target to preprocess a source file
src/split_op.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/split_op.cu.i
.PHONY : src/split_op.cu.i

src/split_op.s: src/split_op.cu.s

.PHONY : src/split_op.s

# target to generate assembly for a file
src/split_op.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/split_op.cu.s
.PHONY : src/split_op.cu.s

src/tracker.o: src/tracker.cu.o

.PHONY : src/tracker.o

# target to build an object file
src/tracker.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/tracker.cu.o
.PHONY : src/tracker.cu.o

src/tracker.i: src/tracker.cu.i

.PHONY : src/tracker.i

# target to preprocess a source file
src/tracker.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/tracker.cu.i
.PHONY : src/tracker.cu.i

src/tracker.s: src/tracker.cu.s

.PHONY : src/tracker.s

# target to generate assembly for a file
src/tracker.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/tracker.cu.s
.PHONY : src/tracker.cu.s

src/unit_test.o: src/unit_test.cu.o

.PHONY : src/unit_test.o

# target to build an object file
src/unit_test.cu.o:
	$(MAKE) -f CMakeFiles/unitTest.dir/build.make CMakeFiles/unitTest.dir/src/unit_test.cu.o
.PHONY : src/unit_test.cu.o

src/unit_test.i: src/unit_test.cu.i

.PHONY : src/unit_test.i

# target to preprocess a source file
src/unit_test.cu.i:
	$(MAKE) -f CMakeFiles/unitTest.dir/build.make CMakeFiles/unitTest.dir/src/unit_test.cu.i
.PHONY : src/unit_test.cu.i

src/unit_test.s: src/unit_test.cu.s

.PHONY : src/unit_test.s

# target to generate assembly for a file
src/unit_test.cu.s:
	$(MAKE) -f CMakeFiles/unitTest.dir/build.make CMakeFiles/unitTest.dir/src/unit_test.cu.s
.PHONY : src/unit_test.cu.s

src/vort.o: src/vort.cu.o

.PHONY : src/vort.o

# target to build an object file
src/vort.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/vort.cu.o
.PHONY : src/vort.cu.o

src/vort.i: src/vort.cu.i

.PHONY : src/vort.i

# target to preprocess a source file
src/vort.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/vort.cu.i
.PHONY : src/vort.cu.i

src/vort.s: src/vort.cu.s

.PHONY : src/vort.s

# target to generate assembly for a file
src/vort.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/vort.cu.s
.PHONY : src/vort.cu.s

src/vortex_3d.o: src/vortex_3d.cu.o

.PHONY : src/vortex_3d.o

# target to build an object file
src/vortex_3d.cu.o:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/vortex_3d.cu.o
.PHONY : src/vortex_3d.cu.o

src/vortex_3d.i: src/vortex_3d.cu.i

.PHONY : src/vortex_3d.i

# target to preprocess a source file
src/vortex_3d.cu.i:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/vortex_3d.cu.i
.PHONY : src/vortex_3d.cu.i

src/vortex_3d.s: src/vortex_3d.cu.s

.PHONY : src/vortex_3d.s

# target to generate assembly for a file
src/vortex_3d.cu.s:
	$(MAKE) -f CMakeFiles/gpue.dir/build.make CMakeFiles/gpue.dir/src/vortex_3d.cu.s
.PHONY : src/vortex_3d.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... unitTest"
	@echo "... gpue"
	@echo "... src/ds.o"
	@echo "... src/ds.i"
	@echo "... src/ds.s"
	@echo "... src/dynamic.o"
	@echo "... src/dynamic.i"
	@echo "... src/dynamic.s"
	@echo "... src/edge.o"
	@echo "... src/edge.i"
	@echo "... src/edge.s"
	@echo "... src/evolution.o"
	@echo "... src/evolution.i"
	@echo "... src/evolution.s"
	@echo "... src/fileIO.o"
	@echo "... src/fileIO.i"
	@echo "... src/fileIO.s"
	@echo "... src/init.o"
	@echo "... src/init.i"
	@echo "... src/init.s"
	@echo "... src/kernels.o"
	@echo "... src/kernels.i"
	@echo "... src/kernels.s"
	@echo "... src/lattice.o"
	@echo "... src/lattice.i"
	@echo "... src/lattice.s"
	@echo "... src/manip.o"
	@echo "... src/manip.i"
	@echo "... src/manip.s"
	@echo "... src/minions.o"
	@echo "... src/minions.i"
	@echo "... src/minions.s"
	@echo "... src/multigpu.o"
	@echo "... src/multigpu.i"
	@echo "... src/multigpu.s"
	@echo "... src/node.o"
	@echo "... src/node.i"
	@echo "... src/node.s"
	@echo "... src/operators.o"
	@echo "... src/operators.i"
	@echo "... src/operators.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/split_op.o"
	@echo "... src/split_op.i"
	@echo "... src/split_op.s"
	@echo "... src/tracker.o"
	@echo "... src/tracker.i"
	@echo "... src/tracker.s"
	@echo "... src/unit_test.o"
	@echo "... src/unit_test.i"
	@echo "... src/unit_test.s"
	@echo "... src/vort.o"
	@echo "... src/vort.i"
	@echo "... src/vort.s"
	@echo "... src/vortex_3d.o"
	@echo "... src/vortex_3d.i"
	@echo "... src/vortex_3d.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

